BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB
  
  BB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
         XXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Replace with another product') 
      XXXX
    XXXXXX
  BBBBB
BBBBBBBB
