BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
  XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
  X XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBXXFFFFFFFFXXXX
  X XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXX
  X XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXX
  X  gettext(u'Replace') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XX  gettext(u'Replace product') 
  XXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXX
      XXXXXXXXXXXXXXXXX  gettext(u'will be permanently replaced.') 
    XXXX
    XXX XXXXXXXXXXXXXXX X X XXXXXXX
      XXXX gettext(u'All related price observations will be reassigned to the selected product.') XXXXX
      XXXX gettext(u'This product record will then be deleted.') XXXXX
    XXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
       gettext(u'This action cannot be undone.') 
    XXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXXXXXX
      XXXXXXXX gettext(u'Select replacement product') XXXXXXXXX
      
    XXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'✅ Confirm replacement') X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Cancel') 
      XXXX
    XXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB
