BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB
  
  BB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Replace with another region') 
      XXXX
    XXXXXX
  BBBBB
BBBBBBBB
