BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX
    XX  gettext(u'Replace region') 
  XXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX  gettext(u'will be permanently replaced.') XXXX
    XXXX
      XXXX gettext(u'All related price observations will be reassigned.') XXXXX
      XXXX gettext(u'This region record will then be deleted.') XXXXX
    XXXXX
    XXXXXX gettext(u'This action cannot be undone.') XXXXXXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Confirm replacement') 
      XXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
         gettext(u'Cancel') 
      XXXX
    XXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB
