# Generated by Django 5.0 on 2025-12-19 07:04

import django.db.models.deletion
import inflation_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name_cyrillic', models.CharField(max_length=255)),
                ('district_name_latin', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'user_organization',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'user_position',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name_cyrillic', models.CharField(max_length=255)),
                ('product_name_latin', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name_cyrillic', models.CharField(max_length=255)),
                ('region_name_latin', models.CharField(max_length=255)),
                ('hc_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='UploadPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code, ex: 'bond_portfolio', 'market_rates'", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Shown in UI, ex: 'Bond Portfolio Upload'", max_length=200)),
                ('upload_path', models.CharField(help_text="Directory where the files will be uploaded, ex: 'bond/'", max_length=255)),
                ('allowed_groups', models.ManyToManyField(to='auth.group')),
            ],
            options={
                'permissions': [('can_upload_{code}', 'Can upload files for {label}')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_contacts', models.CharField(blank=True, help_text="User's mobile phone number(s)", max_length=50, null=True)),
                ('corporate_contacts', models.CharField(blank=True, help_text='Corporate contact details (email or phone)', max_length=1000, null=True)),
                ('department', models.CharField(blank=True, help_text='Department name', max_length=1000, null=True)),
                ('subdivision', models.CharField(blank=True, help_text='Subdivision or section', max_length=1000, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=inflation_app.models.user_profile_picture_path)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='inflation_app.organization')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='inflation_app.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='inflation_app.district')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='inflation_app.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='inflation_app.region')),
            ],
            options={
                'verbose_name': 'Price Observation',
                'verbose_name_plural': 'Price Observations',
                'db_table': 'price_observation',
                'unique_together': {('district', 'product', 'date')},
            },
        ),
    ]
