# Generated by Django 5.0 on 2025-12-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='weights',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
