# Generated by Django 5.0 on 2025-12-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inflation_app", "0002_region_weights"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="priceobservation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="priceobservation",
            constraint=models.UniqueConstraint(
                fields=("district", "product", "date"), name="unique_price_observation"
            ),
        ),
    ]
