# Generated by Django 5.0 on 2026-01-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation_app', '0003_alter_priceobservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_name_russian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_russian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_russian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
