# Generated by Django 5.0 on 2026-01-30 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflation_app', '0004_district_district_name_english_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPIData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('weight', models.FloatField()),
                ('price_change', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpi_data', to='inflation_app.product')),
            ],
            options={
                'verbose_name': 'CPI Data',
                'verbose_name_plural': 'CPI Data',
                'db_table': 'cpi_data',
            },
        ),
        migrations.AddConstraint(
            model_name='cpidata',
            constraint=models.UniqueConstraint(fields=('product', 'year', 'month'), name='unique_cpi_data'),
        ),
    ]
