BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXX
        XXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXX
        XXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX

  XXXX XXXXX XXXX XXXX XXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXX X
    XXXXX XXXXXX
    XXXXX X
        XXXXXXX XBBB BBB BB BBBBBBBBBXXXBBBBBBXX
        XXXXXXXXX XX
            XXXXXX XXXXXXXXXXX
            XXXXX XBBB BBB BB BBBBBBBBBXBBBBBBXX
            XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XX
    X
XXX

XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXX X XXX XXXXXXXXXXXXX X
    XXXXX XXXXXX
    XXXXX X
        XXXXXXX XBBB BBB BB BBBBBBBXXXBBBBBBXX
        XXXXXXXXX XX
            XXXXXX XXXXXXXXXXX
            XXXXX XBBB BBB BB BBBBBBBXBBBBBBXX
            XXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXX
        XX
    X
XXX

XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXX X
    XXXXX XXXXXX
    XXXXX X
        XXXXXXX XBBB BBB BB BBBBBBBBBXFFFFFFFFFFFFFFFFFFFXXBBBBBBXX
        XXXXXXXXX XX
            XXXXXX XXXXXXXXXXX
            XXXXX XBBB BBB BB BBBBBBBBBXBBBBBBXX
            XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XX
    X
XXX
XXXXXXXXX
BBBBBBBB
